# Generated by Django 3.1.2 on 2021-02-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('author_image', models.TextField()),
                ('author_name', models.TextField()),
                ('posting_date', models.DateTimeField()),
                ('text', models.TextField(null=True)),
                ('main_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_history', to='mainApps.posts')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-posting_date'],
            },
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atach_id', models.IntegerField()),
                ('type', models.TextField()),
                ('preview', models.TextField(blank=True)),
                ('url', models.TextField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('connect_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atachs', to='mainApps.posts')),
            ],
        ),
    ]
