# Generated by Django 3.1.4 on 2020-12-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_image', models.TextField()),
                ('author_name', models.TextField()),
                ('post_id', models.IntegerField()),
                ('posting_date', models.DateTimeField()),
                ('text', models.TextField(null=True)),
                ('main_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainApps.posts', verbose_name='copy_history')),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('preview', models.TextField(blank=True)),
                ('url', models.TextField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('connect_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainApps.posts', verbose_name='atachs')),
            ],
        ),
    ]
